// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace AUSKF.Api.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Kendo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Kendo));
        
        string IMigrationMetadata.Id
        {
            get { return "201511040102245_Kendo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return this.Resources.GetString("Target"); }
        }
    }
}
